serverAddr = "103.103.20.44"
serverPort = 7000
auth.token = "0eaf2b88e9ea00e63f04196622f55c5743f06c8545f4f4c33d1741b1031aec89"

[[proxies]]
name = "http"
type = "tcp"
localIP = "nilabiru-nginx-proxy-manager"
localPort = 80
remotePort = 80

[[proxies]]
name = "https"
type = "tcp"
localIP = "nilabiru-nginx-proxy-manager"
localPort = 443
remotePort = 443
