name: Run Github Runners CI/CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          {
            echo "TAILSCALE_IP=${{ secrets.TAILSCALE_IP }}"
            echo "REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}"
            echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}"
            echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}"
            echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}"
            echo "MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}"
            echo "MYSQL_USER=${{ secrets.MYSQL_USER }}"
            echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}"
            echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}"
            echo "MONGO_ROOT_USERNAME=${{ secrets.MONGO_ROOT_USERNAME }}"
            echo "MONGO_ROOT_PASSWORD=${{ secrets.MONGO_ROOT_PASSWORD }}"
            echo "RABBITMQ_USER=${{ secrets.RABBITMQ_USER }}"
            echo "RABBITMQ_PASSWORD=${{ secrets.RABBITMQ_PASSWORD }}"
            echo "RABBITMQ_VHOST=${{ secrets.RABBITMQ_VHOST }}"
            echo "RUSTFS_ACCESS_KEY=${{ secrets.RUSTFS_ACCESS_KEY }}"
            echo "RUSTFS_SECRET_KEY=${{ secrets.RUSTFS_SECRET_KEY }}"
            echo "NEXTCLOUD_DB_NAME=${{ secrets.NEXTCLOUD_DB_NAME }}"
            echo "NEXTCLOUD_ADMIN_USER=${{ secrets.NEXTCLOUD_ADMIN_USER }}"
            echo "NEXTCLOUD_ADMIN_PASSWORD=${{ secrets.NEXTCLOUD_ADMIN_PASSWORD }}"
          } > .env

      - name: Ensure Init Script is Executable
        run: chmod +x init-db.sh

      - name: Validate Docker Compose
        run: docker compose config > /dev/null

      - name: Run Deploy Script
        run: docker compose up -d --remove-orphans

      - name: Cleanup .env
        if: always()
        run: rm -f .env
